/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elearning;

import BLL.*;
import DAL.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Doruntina
 */
public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    StudentiInterface sir = new StudentiRepository();
    LoginInterface lir = new LoginRepository();

    public SignUpForm() {
        this.setUndecorated(true);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        firstNameTxt.setBackground(new Color(0, 0, 0, 0));
        lastNameTxt.setBackground(new Color(0, 0, 0, 0));
        emailTxt.setBackground(new Color(0, 0, 0, 0));
        closeButton.setBackground(new Color(0, 0, 0, 0));
        minimizeButton.setBackground(new Color(0, 0, 0, 0));
        SignUpButton.setBackground(new Color(0, 0, 0, 0));
        interesComboBox.setBackground(new Color(0, 0, 0, 0));
        passwordTxt.setBackground(new Color(0, 0, 0, 0));
        loginButton.setBackground(new Color(0, 0, 0, 0));
        interesComboBox.setBackground(new Color(0, 0, 0, 0));
        firstNameTxt.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (firstNameTxt.getText().equals("Enter First Name")) {
                    firstNameTxt.setText("");
                }
            }
        });
        lastNameTxt.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (lastNameTxt.getText().equals("Enter Last Name")) {
                    lastNameTxt.setText("");
                }
            }
        });
        emailTxt.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (emailTxt.getText().equals("Enter Email")) {
                    emailTxt.setText("");
                }
            }
        });
        passwordTxt.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                passwordTxt.setText("");
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        minimizeButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        interesComboBox = new javax.swing.JComboBox<>();
        firstNameTxt = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        interesLabel = new javax.swing.JLabel();
        fistNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error (1).png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 30, -1));

        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/negative.png"))); // NOI18N
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 30, -1));

        loginButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("or Login");
        loginButton.setOpaque(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 120, 50));

        SignUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_sign-up.png"))); // NOI18N
        SignUpButton.setMaximumSize(new java.awt.Dimension(159, 49));
        SignUpButton.setMinimumSize(new java.awt.Dimension(159, 49));
        SignUpButton.setPreferredSize(new java.awt.Dimension(159, 49));
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 150, -1));

        interesComboBox.setBackground(new java.awt.Color(102, 102, 102));
        interesComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        interesComboBox.setForeground(new java.awt.Color(102, 102, 102));
        interesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Your Interests", "Technology", "Science", "Astronomy" }));
        interesComboBox.setOpaque(false);
        jPanel1.add(interesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 380, 30));

        firstNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        firstNameTxt.setForeground(new java.awt.Color(102, 102, 102));
        firstNameTxt.setText("Enter First Name");
        firstNameTxt.setBorder(null);
        firstNameTxt.setOpaque(false);
        firstNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 370, 30));

        lastNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name");
        jPanel1.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 320, 30));

        lastNameTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lastNameTxt.setForeground(new java.awt.Color(102, 102, 102));
        lastNameTxt.setText("Enter Last Name");
        lastNameTxt.setBorder(null);
        lastNameTxt.setOpaque(false);
        lastNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 370, 30));

        emailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 320, 30));

        emailTxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(102, 102, 102));
        emailTxt.setText("Enter Email");
        emailTxt.setBorder(null);
        emailTxt.setOpaque(false);
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 370, 30));

        passwordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 320, 30));

        passwordTxt.setForeground(new java.awt.Color(102, 102, 102));
        passwordTxt.setText("jPasswordField1");
        passwordTxt.setBorder(null);
        passwordTxt.setOpaque(false);
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        jPanel1.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 380, 30));

        interesLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        interesLabel.setForeground(new java.awt.Color(255, 255, 255));
        interesLabel.setText("Interes");
        jPanel1.add(interesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 320, 30));

        fistNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        fistNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        fistNameLabel.setText("First Name");
        jPanel1.add(fistNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 320, 30));

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 510, 450));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e-learning-vector (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 510, 450));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTxtActionPerformed

    }//GEN-LAST:event_firstNameTxtActionPerformed

    private void lastNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTxtActionPerformed

    }//GEN-LAST:event_lastNameTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed

    }//GEN-LAST:event_emailTxtActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed

        if (!firstNameTxt.getText().equals("")
                && !lastNameTxt.getText().equals("")
                && !emailTxt.getText().equals("")
                && !passwordTxt.getText().equals("")
                && !(passwordTxt.getText().length() < 8)
                && interesComboBox.getSelectedIndex()!= 0) {

            Studenti s = new Studenti();
            Login l = new Login();
            s.setEmri(firstNameTxt.getText());
            s.setMbiemri(lastNameTxt.getText());

            l.setStudentID(s);

            if (emailTxt.getText().matches("^[a-zA-Z0-9\\-\\_\\.]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$")) {
                l.setUsername(emailTxt.getText());
            }
            if (passwordTxt.getText().length() > 8) {
                l.setPassword(passwordTxt.getText());
            }
            if (interesComboBox.getSelectedIndex() != 0) {
                s.setInteresat(interesComboBox.getSelectedItem().toString());
            }

            try {
                sir.create(s);
                lir.create(l);
                SignUpForm sf = new SignUpForm();
                sf.setVisible(false);
                LoginForm lf = new LoginForm();
                lf.setVisible(true);
                this.dispose();
            } catch (eLearningException se) {
                JOptionPane.showMessageDialog(this, se.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(this, "Ju lutem plotesoni fushat obligative!");
        }

    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed

    }//GEN-LAST:event_passwordTxtActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        SignUpForm sf = new SignUpForm();
        sf.setVisible(false);
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignUpButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JLabel fistNameLabel;
    private javax.swing.JComboBox<String> interesComboBox;
    private javax.swing.JLabel interesLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTxt;
    // End of variables declaration//GEN-END:variables
}
